apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "state-sync.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "state-sync.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: {{ include "state-sync.fullname" . }}-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-connection-string
    remoteRef:
      key: {{ .Values.externalSecrets.parameterPaths.databaseConnectionString }}
  - secretKey: the-graph-api-key-cr
    remoteRef:
      key: {{ .Values.externalSecrets.parameterPaths.theGraphApiKeyCR }}
  - secretKey: the-graph-api-key-gov
    remoteRef:
      key: {{ .Values.externalSecrets.parameterPaths.theGraphApiKeyGov }}
