subgraphProviders:
  collective-rewards:
    apiKey: "THE_GRAPH_API_KEY_CR"
  governance:
    apiKey: "THE_GRAPH_API_KEY_GOV"
  usd-vault:
    apiKey: "THE_GRAPH_API_KEY_GOV"
database:
  connectionString: "DATABASE_CONNECTION_STRING"
