app:
  productionMode: true
  initializeDb: true
blockchain:
  network: "testnet"
subgraphProviders:
  collective-rewards:
    id: "deployments/id/QmbCopWKNeFArUuJ5GuG9mGQ9ZNgbdv81UA1b2kiKoEUmB"
  governance:
    id: "deployments/id/QmTsTRSLP5D93ZmLHPu6b4SDq7MwBPsoKJ4P6HGxHeU7vv"
contracts:
  - name: BackersManager
    address: "0x70AC0FE4F8BCA42Aa7e713E1EDA2E8166d0f8Ed8"
  - name: BuilderRegistry
    address: "0xad125E6D5C3B84329fa2466A8A6955F67906F4b2"
  - name: RewardDistributor
    address: "0x35EB7d3e0907BCB838fbA3b08C4c65DB5431169f"
  - name: Governor
    address: "0xB1A39B8f57A55d1429324EEb1564122806eb297F"
