app:
  productionMode: true
  initializeDb: true
blockchain:
  network: "testnet"
subgraphProviders:
  collective-rewards:
    id: "deployments/id/QmdKRP8SbVZA5PvTWkNxHB6LvVcXcFeyQEc9dxu4ccpdo4"
  governance:
    id: "deployments/id/QmaTFz1bQ3GcZQwBGtMWjrHPjbwfiQLRzCeTU2MJ4Z8WyT"
contracts:
  - name: BackersManager
    address: "0x7c2D9C109919B50b9B00Ae173a0398b5EabEE17A"
  - name: BuilderRegistry
    address: "0x543782852C8D5AD54022CaB60FE46578f4141405"
  - name: RewardDistributor
    address: "0x7DbE5169BE874A9C994201b617f8D0378e27cbd9"
  - name: Governor
    address: "0xb77ab0075e9805efa82040bed73368d988a2d9c2"
