app:
  productionMode: true
  initializeDb: true
blockchain:
  network: "mainnet"
subgraphProviders:
  collective-rewards:
    id: "deployments/id/QmNVbEJDoigFnsa3yHQbH7H2BF59U36YkXTfJxevng8VqF"
  governance:
    id: "deployments/id/QmPfqjKsJTfQ22Bo8SgpHdUHS7eywsSvSXX7CdbHHpdBmb"
contracts:
  - name: BackersManager
    address: "0x7995C48D987941291d8008695A4133E557a11530"
  - name: BuilderRegistry
    address: "0x8cb62c58AC3D1253c6467537FDDc563857eD76cb"
  - name: RewardDistributor
    address: "0x5603Ba40257e317e45BA13C3732819Af5E81a9A1"
  - name: Governor
    address: "0x71ac6ff904a17f50f2c07b693376ccc1c92627f0"
