app:
  productionMode: false
  initializeDb: true
database:
  ssl: false
blockchain:
  network: "testnet"
subgraphProviders:
  collective-rewards:
    url: "https://api.studio.thegraph.com/query"
    id: "rootstockcollective-collective-rewards-local/version/latest"
    maxRowsPerRequest: 1000
    apiKey: 106677
  governance:
    url: "https://api.studio.thegraph.com/query"
    id: "rootstock-collective-governance-subgraph/version/latest"
    maxRowsPerRequest: 1000
    apiKey: 56839
  usd-vault:
    url: "https://api.studio.thegraph.com/query"
    id: "usd-vault/version/latest"
    maxRowsPerRequest: 1000
    apiKey: 1714703
contracts:
  - name: BackersManager
    address: "0xb7143af8C7afa3a170E183bE24127bF781Fb89B7"
  - name: BuilderRegistry
    address: "0xDf1ED223f6EC3cC5e57ed5BeaE8031d6BD37516d"
  - name: RewardDistributor
    address: "0xa7CC0f00Ec08F8F4D02Ca8f32aE78b05628c5D69"
  - name: Governor
    address: "0xB1A39B8f57A55d1429324EEb1564122806eb297F"
